---
# tasks file for lb-tier
- name: http
  package:
    name: httpie
    state: latest
  notify: restart_HAProxy

- name: install HAProxy
  yum:
    name: haproxy 
    state: latest
  notify: restart_HAProxy

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_HAProxy
